# Discord Stuff
enabled: true # Enable discord bot?
token: "" # Discord bot token
server: "" # ID of discord server

# Minecraft server display-name
server-name: "occ" # Server name

channels:
  reports: "" # ID of channel where reports are sent
  anticheat: "" # ID of channel where autocheat alerts are sent

# What types of message should be enabled
types:
  reports: true
  relay-command: true

# Reports (Sent from PGM)
#
# Variables
# %server%   - Server Name
# %reporter% - Player who issued report
# %reported% - Player who has been reported
# %reason%   - Reason for report
report-format: "[%server%] **%reporter% reported %reported%: %reason%**"

# Relay - Command based (Used for AutoKiller and via /relay)
#
# Variables
# %server%   - Server Name
# %message%  - Message provided
relay-format: "[%server%] %message%"

# Prefix - Emojis used as a prefix for different message types
prefix:
  report: ":loudspeaker: "
  autokill: ":mouse_three_button: "
  matrix: ":warning: "
  command: ""
  
# Morpheus - Enables clickable and visually enhanced notifications for matric violations.
morpheus:
  enabled: true
  # Permission node requred for viewing altered notifications
  permission-node: matrix.notify
  # Alert prefix used to format notifications
  alert-prefix: "&f[&6AC&f]"
  
  